# The following redirect is intended for use with most SPAs that handle
# routing internally. Without this option page back/forward and refresh
# don't work.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  ## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/headlines"
  to = "https://newsapi.org"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

[build]
  command = "yarn run build"
  functions = "functions" # netlify dev uses this directory to scaffold and serve your functions
  publish = "dist"