# The following redirect is intended for use with most SPAs that handle
# routing internally. Without this option page back/forward and refresh
# don't work.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  